### ISSUE TITLE
Change hover color of link

### ISSUE THREAD

**Issue by smkamranqadri** [devncode/first-contributions#91]
It will be great to change color of links when mouse cursor hover like #2c3e50

Links will be like...
1. Header
2. Github logo
3. link and icons in footer

**Comment by Abhishek-Mittall** [comment]
I can do this

**Comment by smkamranqadri** [comment]
great

**Comment by imSanjaySoni** [comment]
Fixed

**Comment by smkamranqadri** [comment]
@imSanjaySoni it is not, please read the description and test locally.

**Comment by Mihajlo023** [comment]
Is this done? Is it okay if I do it?

**Comment by Mihajlo023** [comment]
Hi @smkamranqadri please take a look at my commit. 
Kind regards,
Mihajlo

**Comment by smkamranqadri** [comment]
@Mihajlo023 no it is not done, please note you need to first take pull as other css is getting removed.

second, please use CSS [BEM](http://getbem.com/introduction/) for naming conventions and avoid child selectors also read the task description so you can understand it properly and ask if any questions.

Important one, please run and test locally before push.

**Comment by RamanaVem** [comment]
Hey @smkamranqadri is this still open? Can i take a look on this?

**Comment by smkamranqadri** [comment]
@RamanaVem Yes, it is please.

**Comment by RamanaVem** [comment]
@smkamranqadri  you didn't mention technologies to run the project. And guidelines too. Can you please help me on this.

**Comment by jsankare** [comment]
Hey, do you mind if I give it a try ? @smkamranqadri

**Comment by smkamranqadri** [comment]
Yeah, it's based on jekyll so you need to install ruby, gem and of course jekyll.

**Comment by smkamranqadri** [comment]
Run this command to serve in dev mode.

jekyll s --livereload --incremental
